### ISSUE TITLE
Create Installer

### ISSUE THREAD

**Issue by hcsdrose** [abreio/Abre-Conduct#1]
CREATE TABLE `conduct_colors` (
  `ID` int(11) NOT NULL,
  `StudentID` text NOT NULL,
  `Color` text NOT NULL,
  `Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CourseGroup` text NOT NULL,
  `Section` text NOT NULL,
  `StaffID` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `conduct_discipline`
--

CREATE TABLE `conduct_discipline` (
  `ID` int(11) NOT NULL,
  `Submission_Time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Incident_Date` text NOT NULL,
  `Incident_Time` text NOT NULL,
  `Owner` text NOT NULL,
  `Owner_Name` text NOT NULL,
  `Building` text NOT NULL,
  `SchoolCode` text NOT NULL,
  `Type` text NOT NULL,
  `StudentID` text NOT NULL,
  `Student_IEP` text NOT NULL,
  `Student_FirstName` text NOT NULL,
  `Student_LastName` text NOT NULL,
  `Offence` text NOT NULL,
  `Location` text NOT NULL,
  `Description` text NOT NULL,
  `Information` text NOT NULL,
  `Consequence` text NOT NULL,
  `Served` int(11) NOT NULL DEFAULT '0',
  `Teacher_Served` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `conduct_colors`
--
ALTER TABLE `conduct_colors`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `conduct_discipline`
--
ALTER TABLE `conduct_discipline`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `conduct_colors`
--
ALTER TABLE `conduct_colors`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `conduct_discipline`
--
ALTER TABLE `conduct_discipline`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT;

Ideal date to be completed: After pdfs are being created (when possible).

**Comment by wilso199** [comment]
Implemented. Pull request #4 will close this issue when merged.
