### ISSUE TITLE
View All Students when Submission

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Conduct#12]
When adding a student to a consequence, a principal can view ALL students within the district. This is problematic:

1. Common lastnames (ie Smith) don't all appear. I suspect the return variable only grabs the first 10 from the database?
2. Principals don't really need to see students from other buildings.

**Comment by hcsdrose** [comment]
Line 45 in search.php - if(superadmin() or AdminCheck($_SESSION['useremail'])==1)

needs to be corrected to - if(superadmin())

**Comment by hcsdrose** [comment]
Addressed in 0.2.8
