### ISSUE TITLE
PDF Merged Form Data

### ISSUE THREAD

**Issue by hcsdrose** [abreio/Abre-Conduct#2]
Give admins the ability to print out a pdf that a student/parent can sign containing information saved from the submitted incident. There are 12 total pdf templates.

Ideal Date to be completed (one pdf form): July 1st, 2017

**Comment by wilso199** [comment]
Framework is in place for this and will be resolved with #4 . Still waiting for word document files to make a more detailed pdf generation.

**Comment by wilso199** [comment]
All PDFs complete and in #6 pending review
