### ISSUE TITLE
Multi Consequence Modal Bug 

### ISSUE THREAD

**Issue by wilso199** [abreio/Abre-Conduct#20]
If a user clicks the add button, on any display, clicks off the modal, and then returns to the modal, the add button will still add a new row, however that row will have an id 1 higher than it should be.

For example: two consequences are already set on rows 0 and 1. I click the add button row 2 should come up. I enter no values to that row so it should not save. If I click off modal and click back on to the modal then click the add button row 0,1, and 3 will be showing. 

This will cause issues with submitting.

**Comment by hcsdrose** [comment]
@wilso199 Is this still a bug?

**Comment by wilso199** [comment]
@hcsdrose fixed with #23

**Comment by wilso199** [comment]
@hcsdrose this issue can be closed. Unless you are waiting for 0.3.7 to be released
