### ISSUE TITLE
Conduct Monitor Saving Conduct Serve and Overwriting Data

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Conduct#32]
Users who have the conduct verification role can, on submission, submit empty fields on the fields they're not allowed to view (ie consequence) which overwrites the incident.

**Comment by hcsdrose** [comment]
@wilso199 Is this still an issue? Have we been able to see this in action?

**Comment by zjvv** [comment]
Closing issue. Solved with 84796a8 merge.
