### ISSUE TITLE
Capture user assigning consequence

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Conduct#38]
Request from the schools: Auto-recording who assigns the consequence.

**The issue**
After creating an incident, the administrator receives issue in their queue. When they assign the consequence, their username is not recorded in the database.

**The desire** 
Admins would like their username recorded. This helps in large buildings when parents come calling and need to get the story (ie - to know which admin took the lead on assigning the consequence).

**Posible Solution:** 
Add a column to CONDUCT_DISCIPLINE_CONSEQUENCES table that records user.

**Comment by wilso199** [comment]
Closed with #39 @zjvv
