### ISSUE TITLE
Give admins the ability to view personal referrals

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Conduct#49]
I know, we left this out on purpose. But the overwhelming feedback we're getting from all stakeholders is this needs to be enabled. Admins want the ability to view the "big picture" when it comes to discipline.

**Comment by hcsdrose** [comment]
To be clear. They just want view access of personal conduct correct? If so this should be added to the students app.

**Comment by zjvv** [comment]
Correct. Closing issue, opening it in students app.
