### ISSUE TITLE
Spelling Issue

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Conduct#52]
From end user :)

"No Contact Order" is listed as "No Contract Order" on the drop down choices for consequences, and the header reads "Offences" instead of "Offenses", just in case you wanted feedback on minuscule things.

**Comment by hcsdrose** [comment]
We will fix the "No Contact Order". There are 2 different spellings for Offence/Offense. We tried to stay consistent - http://www.dictionary.com/browse/offence

**Comment by wilso199** [comment]
"No Contract Order" should now display properly. Fixed with #53.
